# Generated by Django 5.2.4 on 2025-07-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Alimentação', 'Alimentação'), ('Transporte', 'Transporte'), ('Lazer', 'Lazer'), ('Contas', 'Contas')], max_length=50)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
